### ISSUE TITLE
Clean up wording of MnM rule

### ISSUE THREAD

**Issue by highlyunavailable** [wcmille/GVAS2#112]
From discord: https://discord.com/channels/470362839752900608/568860404231438346/1179636854069416018

> 1 MNM Manufacturing & Maintenance block per grid. No subgridding to get around the limit. This works similar to Build and Repair.

This appears to be a legacy rule and the wording should probably be cleaned up or removed.

**Comment by wcmille** [comment]
I've removed the rule.
