### ISSUE TITLE
Reduce Farpoint ingot buy volume for rares, increase it for less rare materials

### ISSUE THREAD

**Issue by highlyunavailable** [wcmille/GVAS2#140]
Part of the reason that I had such a runaway income was Farpoint had massive buy orders for goods. Make me spread out my sales somehow or take losses to sell to lower priced orders (e.g. the Cities on planets.)

Stuff like Silver had too low a buy quantity, stuff like Plat should have stayed at ~500 and cities/refineries should have picked up the slack but at a discount. See #131.

**Comment by wcmille** [comment]
I think the question is really -- can that station *sell* those materials. If I were a trade station, I would definitely be buying as much of something as I think I could sell at a profit.

**Comment by wcmille** [comment]
I've rebalanced the SESE amounts based on the S2 data.
