### ISSUE TITLE
Make Small missile launchers able to launch their allowed ammos to their full potential

### ISSUE THREAD

**Issue by highlyunavailable** [wcmille/GVAS2#144]
Make the small grid turrets/launchers able shoot the missile its full range. This means set the turret range of the small grid missile turret and reloadable launcher to 2500m. It's the same ammo, the rocket isn't any different between the launchers, there are just fewer tubes. 600m makes the small turret really useless, when it's actually a solid defense against PMWs with an archer loaded if it could reach out to 2500m to shoot. Small grid reloadable launchers similarly are shortened to ~1800 m, not 2500.

**Comment by wcmille** [comment]
I've set the "small missiles" to 4km, crusaders to 5km.

**Comment by wcmille** [comment]
Should be all missiles can shoot 4km now.
