### ISSUE TITLE
Put the ammo type at the front of the ammo name so it shows up right on the toolbar

### ISSUE THREAD

**Issue by highlyunavailable** [wcmille/GVAS2#145]
This isn't great - is this AP or flak?
![image](https://github.com/wcmille/GVAS2/assets/6266125/499b2a69-9f22-495a-aae6-9de578f62a7a)

This is great, I know exactly what's going into the tubes.
![image](https://github.com/wcmille/GVAS2/assets/6266125/24323a59-7cea-4d6d-be88-cb14fd33f16b)

The request is to change the subtype ID of the ammos so that they are immediately identifiable in ~6-8 characters on hotbars.

**Comment by wcmille** [comment]
This might break all the prefabs. I'll have to do this after the server has been passworded.
