### ISSUE TITLE
Suggestion: Remove the pirate marches and move far point closer to the planet

### ISSUE THREAD

**Issue by SiliconMoose** [wcmille/GVAS2#152]
Having such a huge area of space for players to spawn in and get lost in basically makes it impossible for players to ever run into each other outside the planet.

Additionally, traversing the pirate marches has no risks or even likelihood of encountering anyone as is, so going from the planet to farpoint to trade inevitably involves sitting in the middle of nowhere for seven minutes each way while your drives charge again to make the rest of the jump. Which is very boring.

Even with the "hot" beacon from jumps, the chances of anyone being near enough to the spot you landed to even **see** you is so small it may as well not even be considered.

**Comment by wcmille** [comment]
I need the black zone as a place red and blue players can go to destroy pirates to actively reduce pirate forces. This is a very tough zone -- I like your intermediate area -- so it's probably good that players can't stumble in.
