### ISSUE TITLE
Suggestion: Add new ores and specialized components to moderate access to power weapons

### ISSUE THREAD

**Issue by SiliconMoose** [wcmille/GVAS2#155]
Given GVA's overall industrial theme, using data cards as a way to control access to higher power weapons doesn't make much sense, but needing specific elements to make rare materials does. Additionally, GVA's much stronger reliance on mining compared to GVK makes specialized ores and metals a natural solution to creating scarce components. 

Potential materials and recipe changes

Aluminum
- Available in small quantities in space, more available on planet
- Used for to create "Synthetic Ruby" for laser weapons. 
- Added to railgun rounds recipe 

Ruthenium
- Only available on the planet
- Used to create "Conductive Ceramic" used in all railgun weapons (maybe with Silicon, Iron and/or platinum)

Graphene (Carbon)
- Available everywhere (hydrocarbon ice (space), coal (planet) or as a byproduct of refining stone), but takes a **very** long time to refine
- Used to produce "Supercapacitor", needed for both lasers and rail weapons (replace Power Cells in rail weapons)

A few mods to supply ore voxel materials and icons
https://steamcommunity.com/sharedfiles/filedetails/?id=2407189819
https://steamcommunity.com/sharedfiles/filedetails/?id=2841960221
https://steamcommunity.com/sharedfiles/filedetails/?id=2344068716

**Comment by wcmille** [comment]
Might considers ores and components for a later season. (S4 or later)
