### ISSUE TITLE
Torpedo max trajectory doesn't match or exceed its targeting distance

### ISSUE THREAD

**Issue by tinsoldier** [wcmille/GVAS2#160]
Testing out the new torpedo changes and I was unable to fire at a target 4.3kms away. Looking at the defs, the torpedo weapon has a max target distance of 5km but the ammo has a max trajectory of 4km. Changing my local settings to 5k+ on the ammo allowed me to successfully hit the 4.3km target.

**Comment by wcmille** [comment]
Good catch. I checked the other missiles and updated those also. It's uploaded to github, and will go out with my next Steam update.
