### ISSUE TITLE
Reloadable rocket launchers should probably hold more than 1.5 volleys.

### ISSUE THREAD

**Issue by highlyunavailable** [wcmille/GVAS2#161]
![image](https://github.com/wcmille/GVAS2/assets/6266125/c55c4cda-35c8-490f-a0b7-67e7ee1a6069)

Upgrade it to 8 missiles possibly?

**Comment by wcmille** [comment]
Wanted to be consistent about 1 load per launcher with the others. Updated all the launchers as appropriate.
